apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.env}}-documentclassifications-com-tls
  namespace: istio-system
spec:
  secretName: {{ .Values.env}}-documentclassifications-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.env}}.documentclassifications.com