apiVersion: v1
kind: Service
metadata:
  name: clamav-service
  namespace: {{ .Values.env }}-document-classification
spec:
  selector:
    app: clamav
  ports:
  - port: 3310
    targetPort: 3310
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  namespace: {{ .Values.env }}-document-classification
  labels:
    app: clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav
  template:
    metadata:
      namespace: {{ .Values.env }}-document-classification
      labels:
        app: clamav
    spec:
      containers:
        - name: clamav
          image: clamav/clamav:1.4.2
          ports:
            - containerPort: 3310
          startupProbe:
            tcpSocket:
              port: 3310
            periodSeconds: 1
            timeoutSeconds: 1
            failureThreshold: 120
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 3310
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: 3310
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: 3000Mi
              cpu: 1000m
            limits:
              memory: 4000Mi
              cpu: 1200m