apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: documentclassifications-com-tls
  namespace: istio-system
spec:
  secretName: documentclassifications-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - dev.documentclassifications.com