apiVersion: v1
kind: Service
metadata:
  name: document-classification-api
  namespace: document-classification
  labels:
    app: web_app
spec:
    type: ClusterIP
    selector:
        app: web_app
    ports:
        - port: 80
          targetPort: 8080